# Scalability-참여자 수 — 메시지 확장 지수 b_msg (25) · 정적 벤치마크 family 기준

- 실행: 2026-08-11T05:59:03+00:00 · run_id `scalability-20260811T055903Z`
- 입력: **정적 벤치마크 family** `data/benchmark/cases/scalability/participants` — 무작위 생성기가 아니다
- 표본: 케이스 180건 · family 30개 · N ∈ [3, 4, 5, 6, 8, 10] · k 분포 k=1 family 10개 · k=2 family 10개 · k=3 family 10개
- 실행: 케이스마다 두 방안 각 1회 (`collect_log=False`) · 세션 360건
- 환경: python 3.14.6 · negmas 0.15.7
- 설계 근거: family는 N이 늘어도 **기존 참여자 프로파일과 후보 목록이 그대로 유지**되고 공통 실후보 수 k가 N과 무관하게 고정된다 (25 §25.5 난이도 교락 통제)

## [1] 전체 — b_msg (k=1/2/3 통합)

| 방안 | 완결률 게이트 | b_msg [95% CI] | R² | 별점 | 메시지 중앙값 (N별) |
|---|---|---|---|---|---|
| plan1 | 통과 N=3 30/30 vs N=10 30/30 | 1.465 [1.33, 1.60] ⚠CI 3등급 | 0.995 | ★★☆☆☆ (2점) | N3:64 N4:107 N5:150 N6:192 N8:284 N10:380 |
| plan2 | 통과 N=3 30/30 vs N=10 30/30 | 1.500 [1.26, 1.74] ⚠CI 3등급 | 0.987 | ★★☆☆☆ (2점) | N3:20 N4:36 N5:52 N6:65 N8:97 N10:127 |

## [2] k별 — 사전 실험 (25 §25.5의 'k는 사전 실험으로 정해 고정' 요구에 대응)

25 §25.5는 난이도 교락 통제용 공통 실후보 수 k를 사전 실험으로 정해 실험 설계서에 고정하라고 요구하지만, 그 사전 실험은 수행된 적이 없다. **아래 표가 그 사전 실험이다** — k를 바꾸면 b_msg 별점이 몇 등급 움직이는지가 산출물이다.

| 방안 | k | 케이스 | 완결률 게이트 | b_msg [95% CI] | R² | 별점 | 메시지 중앙값 (N별) |
|---|---|---|---|---|---|---|---|
| plan1 | k=1 | 60 | 통과 N=3 10/10 vs N=10 10/10 | 1.395 [1.27, 1.53] | 0.996 | ★★★☆☆ (3점) | N3:68 N4:101 N5:134 N6:190 N8:278 N10:348 |
| plan1 | k=2 | 60 | 통과 N=3 10/10 vs N=10 10/10 | 1.457 [1.29, 1.62] ⚠CI 3등급 | 0.994 | ★★☆☆☆ (2점) | N3:64 N4:110 N5:150 N6:196 N8:282 N10:382 |
| plan1 | k=3 | 60 | 통과 N=3 10/10 vs N=10 10/10 | 1.647 [1.19, 2.11] ⚠CI 3등급 | 0.961 | ★☆☆☆☆ (1점) | N3:48 N4:116 N5:158 N6:198 N8:300 N10:394 |
| plan2 | k=1 | 60 | 통과 N=3 10/10 vs N=10 10/10 | 1.508 [1.29, 1.72] ⚠CI 3등급 | 0.990 | ★★☆☆☆ (2점) | N3:20 N4:34 N5:50 N6:64 N8:92 N10:124 |
| plan2 | k=2 | 60 | 통과 N=3 10/10 vs N=10 10/10 | 1.521 [1.34, 1.70] ⚠CI 3등급 | 0.993 | ★★☆☆☆ (2점) | N3:20 N4:34 N5:52 N6:64 N8:98 N10:130 |
| plan2 | k=3 | 60 | 통과 N=3 10/10 vs N=10 10/10 | 1.648 [1.21, 2.08] ⚠CI 3등급 | 0.965 | ★☆☆☆☆ (1점) | N3:16 N4:37 N5:54 N6:66 N8:101 N10:131 |

**k 민감도 — 별점 이동 폭**

| 방안 | k별 별점 | 별점 이동 | k별 b_msg | b_msg 폭 |
|---|---|---|---|---|
| plan1 | k1:3점 / k2:2점 / k3:1점 | **2등급** | k1:1.395 / k2:1.457 / k3:1.647 | 0.251 |
| plan2 | k1:2점 / k2:2점 / k3:1점 | **1등급** | k1:1.508 / k2:1.521 / k3:1.648 | 0.140 |

> 해석: 별점 이동 폭이 0등급이면 k 선택이 판정에 영향을 주지 않으므로 실험 설계서에 어떤 k를 고정해도 무방하다. 1등급 이상이면 k를 고정하지 않은 측정은 등급을 신뢰할 수 없다.

## [3] 보조 관측 (25 §25.6 — 판정에는 쓰지 않음)

| 방안 | R² | 라운드 중앙값 (N별) | phase 중앙값 (N별) |
|---|---|---|---|
| plan1 | 0.995 | N3:8 N4:9 N5:10 N6:10 N8:10 N10:11 | N3:33 N4:37 N5:40 N6:41 N8:43 N10:45 |
| plan2 | 0.987 | N3:10 N4:14 N5:15 N6:15 N8:16 N10:17 | N3:12 N4:14 N5:16 N6:16 N8:17 N10:18 |

- **부하 편중(최대÷평균)**: 생략 — 노드별 처리 건수는 Blackboard.load 에만 있고 SessionResult 로 전달되지 않는다(protocol.py 의 run() 이 Blackboard 를 로컬로 유지). src 수정 없이는 얻을 수 없어 이번 측정에서는 산출하지 않았다.
- R² < 0.9면 멱 모형 부적합 신호 (§25.6) — 위 표의 R²로 확인한다.

## [4] 기존 생성기 기반 측정과의 비교

기존 생성기 기반 측정은 N 수준마다 프로파일을 통째로 새로 뽑아 N 사이에 '문제 자체가 달라지는' 분산이 섞여 들어갔고, 신뢰구간이 3등급에 걸쳤다. 이 family 설계는 **N이 늘어도 기존 참여자 프로파일이 그대로 유지**되므로 N 사이의 차이가 참여자 추가분으로만 생긴다 — 두 결과를 비교하면 그 효과가 보인다.

| 방안 | 입력 | b_msg [95% CI] | CI 폭 | R² | 별점 | CI 3등급 |
|---|---|---|---|---|---|---|
| plan1 | 생성기 `20260811T050518Z` (ControlledTableUfun(k=3)) | 1.466 [1.33, 1.60] | 0.275 | 0.996 | ★★☆☆☆ (2점) | 예 |
| plan1 | **정적 family (본 측정)** | 1.465 [1.33, 1.60] ⚠CI 3등급 | 0.276 | 0.995 | ★★☆☆☆ (2점) | 예 |
| plan2 | 생성기 `20260811T050518Z` (ControlledTableUfun(k=3)) | 1.428 [1.25, 1.60] | 0.349 | 0.992 | ★★☆☆☆ (2점) | 예 |
| plan2 | **정적 family (본 측정)** | 1.500 [1.26, 1.74] ⚠CI 3등급 | 0.477 | 0.987 | ★★☆☆☆ (2점) | 예 |

**관측된 CI 폭 변화**: plan1 0.275 → 0.276 (확대) · plan2 0.349 → 0.477 (확대)

> **주의 — 위 설계 논리가 이번 데이터에서는 확인되지 않았다.** family 입력에서도 CI가 좁아지지 않았고 CI는 여전히 3등급에 걸친다. 즉 CI 폭을 지배하는 것은 N 사이의 프로파일 변동이 아니라 **N 수준이 6개뿐이라 회귀 자유도가 4**라는 점이다(loglog_fit 은 N 수준별 중앙값 1점씩만 적합한다 — family를 늘려도 회귀점 수는 그대로다). 등급 확정에는 N 수준 추가가 필요하며, family 설계의 값어치는 CI 폭이 아니라 **난이도 교락이 제거된 b_msg 점추정의 타당성**에서 찾아야 한다.

